## run NetREX 1 with Kellis prior

- Need updated S2 cell expression matrix from Justin
- Need to download and import/ look at Kellis prior

In [1]:
import pandas as pd

In [2]:
#read expression matrix

rpkm_cnts = pd.read_table('../output/rna_seq/s2_rnaseq_rpkm_20181025.tsv', index_col=0)
rpkm_cnts.head()

,ERX173563,ERX173565,ERX173570,ERX173571,ERX173572,ERX173578,ERX173581,ERX173588,ERX173594,ERX173597,...,SRX982550,SRX982551,SRX982552,SRX982553,SRX984881,SRX984882,SRX984883,SRX984887,SRX984888,SRX984889
FBgn,,,,,,,,,,,,,,,,,,,,,
FBgn0000003,4.693087,18.059926,3.502857,3.489060,8.805346,1.357878,2.854273,8.300369,2.412581,3.597685,...,1509.384039,457.664859,975.877551,1324.676476,333.647064,335.659324,337.877275,325.630278,331.196901,350.104401
FBgn0000008,1.036744,0.997399,0.633119,0.722591,0.000000,0.824910,1.024618,1.069614,1.598881,0.645743,...,2.256546,3.696423,3.044996,3.470431,3.071065,2.928488,3.056046,3.218800,2.770363,2.841103
FBgn0000014,0.000000,0.000000,0.017384,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.187037,0.160476,0.434130,0.234253,0.000000,0.009460,0.000000,0.000000,0.016497,0.000000
FBgn0000015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.083662,0.163419,0.268875,0.191026,0.000000,0.000000,0.005946,0.007353,0.000000,0.000000
FBgn0000017,11.055975,18.113462,10.992803,5.961193,17.457513,7.632993,16.577228,11.938917,12.323756,13.048799,...,36.191600,25.384579,19.064768,20.239673,27.591561,27.493040,27.033523,31.956844,31.809591,30.744527

In [3]:
filter_rpkm = rpkm_cnts[rpkm_cnts.max(axis=1) > 4]

In [4]:
filter_rpkm.shape

(12742, 542)

In [26]:
#read supervised FlyNet prior from Marbach et al

prior = pd.read_table('../data/flynet_supervised_0.6.txt', header=None, names=['TF','gene', 'weight'])
prior.head()

            TF         gene   weight
0  FBgn0004110  FBgn0035954  0.98264
1  FBgn0035769  FBgn0000541  0.97961
2  FBgn0004110  FBgn0004009  0.97875
3  FBgn0004110  FBgn0004862  0.97768
4  FBgn0002914  FBgn0015664  0.97735

In [27]:
matrix_prior = prior.set_index(['gene','TF']).unstack().fillna(value=0)

In [28]:
matrix_prior.shape

(12286, 617)

In [29]:
good_idx = filter_rpkm.index.intersection(matrix_prior.index)

In [30]:
idx_rpkm = filter_rpkm.loc[good_idx]
idx_prior = matrix_prior.loc[good_idx]

In [31]:
print(idx_rpkm.shape, idx_prior.shape)

(9038, 542) (9038, 617)

In [33]:
idx_rpkm.to_csv('../output/s2cell_rpkm_idx_for_netrex', sep='\t', header=None)

In [38]:
idx_prior.columns = idx_prior.columns.get_level_values(1)
idx_prior.index.name = None
idx_prior.columns.name = None
idx_prior.head()

,FBgn0000014,FBgn0000015,FBgn0000022,FBgn0000028,FBgn0000054,FBgn0000061,FBgn0000097,FBgn0000099,FBgn0000137,FBgn0000157,...,FBgn0259789,FBgn0259938,FBgn0260243,FBgn0260632,FBgn0260642,FBgn0260741,FBgn0260789,FBgn0261239,FBgn0261434,FBgn0261648
FBgn0000008,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0
FBgn0000015,0.93048,0.0,0.0,0.0,0.88691,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.90581,0.0,0.0,0.0,0.62698,0.0
FBgn0000017,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0
FBgn0000018,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0
FBgn0000022,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.00000,0.0

In [39]:
#idx_prior.to_csv('../output/kellis_prior_idx_for_netrex', sep='\t')

In [41]:
trim_zeros_prior = idx_prior.loc[:, (idx_prior != 0).any(axis=0)]

In [42]:
trim_zeros_prior.to_csv('../output/kellis_prior_idx_for_netrex', sep='\t')